
TARGET = arduino_promicro
TARGET_PATH = ./arduino_promicro
PARENT_PATH = ./..
MCU = atmega32u4
F_CPU = 16000000
LWCLONE_SRC = ../main_usb.c ../descriptors.c ../comm.c ../led_toys_pwm.c ../panel.c ../queue.c ../clock.c ../mpu6050.c ../twi.c

include ../lufa.mk
